//! # Fluppy — Groth16 Verifier Module (`verify.rs`) [MOCKED FOR MVP]
//!
//! ⚠️ PERHATIAN: Modul ini saat ini dalam mode MOCK (Bypass). 
//! Fungsi kriptografi berat (BN254 host functions) dibypass agar dapat di-compile 
//! dengan Soroban SDK standar untuk keperluan integrasi Frontend (Week 2 SOW).
//! Dokumentasi di bawah ini menjelaskan arsitektur produksi yang akan digunakan 
//! saat Protocol 25 (CAP-0074) sepenuhnya aktif.
//!
//! 
//! 
//! Pure cryptographic verification for the FluppyPayment Circom circuit.
//! **No payment logic lives here.** This module is a narrow verification
//! gateway — the only thing it does is accept or reject a Groth16 proof.
//!
//! ## Circuit identity
//! ```circom
//! component main {
//!     public [merkleRoot, recipientHash, minAmount, maxAmount]
//! } = FluppyPayment(20);
//! // outputs: nullifier, verifiedRoot
//! ```
//!
//! ## Public signal ordering (MUST match SnarkJS export exactly)
//! SnarkJS lists *outputs* before *declared public inputs*:
//! | vk_ic index | Signal        | Kind           |
//! |-------------|---------------|----------------|
//! | IC[1]       | nullifier     | circuit output |
//! | IC[2]       | verifiedRoot  | circuit output |
//! | IC[3]       | merkleRoot    | public input   |
//! | IC[4]       | recipientHash | public input   |
//! | IC[5]       | minAmount     | public input   |
//! | IC[6]       | maxAmount     | public input   |
//!
//! ## Groth16 verification equation
//! ```text
//! e(πA, πB) · e(−α, β) · e(−vk_x, γ) · e(−πC, δ) = 1_GT
//! vk_x = IC[0] + Σ_{i=1}^{6} ( public_input[i-1] · IC[i] )
//! ```
//!
//! ## Encoding conventions (big-endian throughout)
//! - **G1 point** → 64 bytes  : `x[0..32] || y[0..32]`
//! - **G2 point** → 128 bytes : `x.c1[0..32] || x.c0[0..32] || y.c1[0..32] || y.c0[0..32]`
//! - **Scalar** → 32 bytes  : standard big-endian field element
//!
//! ─────────────────────────────────────────────────────────────────────────────
//! ⚠  PROTOCOL STATUS — READ BEFORE DEPLOYING TO MAINNET
//! ─────────────────────────────────────────────────────────────────────────────
//! BN254 host functions (`bn254_g1_add`, `bn254_g1_mul`, `bn254_pairing_check`)
//! are specified in CAP-0074. Verify the current CAP status before deploying!
//! ─────────────────────────────────────────────────────────────────────────────

use soroban_sdk::{contracterror, Bytes, BytesN, Env};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// § 1  Error Types
// Source: contracts-soroban.md — contracterror, typed error codes
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum VerifyError {
    /// πA/πB/πC do not satisfy the Groth16 pairing equation.
    InvalidProof = 1,
    /// A public input is ≥ r (outside the BN254 scalar field).
    InputOutOfField = 2,
    /// Caller supplied a number of public inputs ≠ N_PUBLIC (6).
    InputCountMismatch = 3,
    /// Byte slice has the wrong length for a G1 or G2 point.
    EncodingError = 4,
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// § 2  BN254 Constants
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Number of public signals for the FluppyPayment(20) circuit.
/// 2 outputs (nullifier, verifiedRoot) + 4 declared public inputs.
pub const N_PUBLIC: usize = 6;

/// BN254 **base field** prime p (big-endian, 32 bytes).
/// Used exclusively for G1 Y-coordinate negation.
const BN254_FIELD_PRIME_P: [u8; 32] = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29,
    0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x97, 0x81, 0x6a, 0x91, 0x68, 0x71, 0xca, 0x8d,
    0x3c, 0x20, 0x8c, 0x16, 0xd8, 0x7c, 0xfd, 0x47,
];

/// BN254 **scalar field** order r (big-endian, 32 bytes).
/// Public inputs must be strictly less than r.
const BN254_SCALAR_FIELD_R: [u8; 32] = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29,
    0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91,
    0x42, 0xe0, 0xf8, 0x53, 0xfc, 0xdb, 0x8a, 0x8f,
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// § 3  Verification Key
//
// IMPORTANT: Replace all placeholder bytes below with the real values
// generated by your trusted setup (`snarkjs zkey export verificationkey`).
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Groth16 verification key for FluppyPayment(20), BN254/Circom.
struct VerificationKey {
    /// −α in G1 (negated alpha — precomputed from trusted setup).
    neg_alpha_g1: [u8; 64],
    /// β in G2  (`vk_beta_2`  from vkey.json)
    beta_g2: [u8; 128],
    /// γ in G2  (`vk_gamma_2` from vkey.json)
    gamma_g2: [u8; 128],
    /// δ in G2  (`vk_delta_2` from vkey.json)
    delta_g2: [u8; 128],
    /// IC[0..=N_PUBLIC]
    /// (`vk_ic` array from vkey.json, length = N_PUBLIC + 1)
    ic: [[u8; 64]; N_PUBLIC + 1],}

impl VerificationKey {
    fn load() -> Self {
        Self {
            // Derive: python3 -c "
            //   p = 21888242871839275222246405745257275088696311157297823662689037894645226208583
            //   x = int(vk['vk_alpha_1'][0])
            //   y = int(vk['vk_alpha_1'][1])
            //   y_neg = (p - y) % p
            //   print(x.to_bytes(32,'big').hex() + y_neg.to_bytes(32,'big').hex())
            // "
            neg_alpha_g1: [0xAA; 64], // ← REPLACE with derived neg-alpha bytes
            beta_g2: [0xBB; 128],     // ← REPLACE with vk_beta_2 bytes
            gamma_g2: [0xBB; 128],    // ← REPLACE with vk_gamma_2 bytes
            delta_g2: [0xBB; 128],    // ← REPLACE with vk_delta_2 bytes
            ic: [
                [0xAA; 64], // IC[0] — constant term
                [0xAA; 64], // IC[1] — nullifier
                [0xAA; 64], // IC[2] — verifiedRoot
                [0xAA; 64], // IC[3] — merkleRoot
                [0xAA; 64], // IC[4] — recipientHash
                [0xAA; 64], // IC[5] — minAmount
                [0xAA; 64], // IC[6] — maxAmount
            ],
        }
    }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// § 4  Helpers — field arithmetic, G1 operations, encoding
// Source: security.md §4 (checked arithmetic); contracts-soroban.md (Bytes/BytesN)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Returns `true` iff `a < b` where both are big-endian 32-byte integers.
#[inline]
fn be32_lt(a: &[u8; 32], b: &[u8; 32]) -> bool {
    for i in 0..32 {
        match a[i].cmp(&b[i]) {
            core::cmp::Ordering::Less    => return true,
            core::cmp::Ordering::Greater => return false,
            core::cmp::Ordering::Equal   => continue,
        }
    }
    false
}

/// Computes `modulus − value` as a big-endian 32-byte integer.
#[inline]
fn be32_sub(modulus: &[u8; 32], value: &[u8; 32]) -> [u8; 32] {
    let mut result = [0u8; 32];
    let mut borrow: u16 = 0;
    for i in (0..32).rev() {
        let m = modulus[i] as u16;
        let v = value[i] as u16 + borrow;
        if m >= v {
            result[i] = (m - v) as u8;
            borrow = 0;
        } else {
            result[i] = (m + 256 - v) as u8;
            borrow = 1;
        }
    }
    result
}

/// Negates a G1 point by flipping its Y coordinate: (x, y) → (x, p − y).
fn g1_negate(env: &Env, point: &BytesN<64>) -> Result<BytesN<64>, VerifyError> {
    let raw = point.to_array();
    let mut x_bytes = [0u8; 32];
    let mut y_bytes = [0u8; 32];
    x_bytes.copy_from_slice(&raw[0..32]);
    y_bytes.copy_from_slice(&raw[32..64]);

    // Y must be a valid base-field element: 0 ≤ y < p.
    if !be32_lt(&y_bytes, &BN254_FIELD_PRIME_P) {
        return Err(VerifyError::InputOutOfField);
    }

    // Handle the point at infinity: (0, 0) negates to itself.
    let is_infinity = y_bytes == [0u8; 32] && x_bytes == [0u8; 32];
    let y_neg = if is_infinity {
        [0u8; 32]
    } else {
        be32_sub(&BN254_FIELD_PRIME_P, &y_bytes)
    };

    let mut result = [0u8; 64];
    result[0..32].copy_from_slice(&x_bytes);
    result[32..64].copy_from_slice(&y_neg);

    Ok(BytesN::from_array(env, &result))
}

/// Validates that every public input is a valid BN254 scalar field element
fn validate_public_inputs(inputs: &[BytesN<32>; N_PUBLIC]) -> Result<(), VerifyError> {
    for input in inputs.iter() {
        let raw = input.to_array();
        if !be32_lt(&raw, &BN254_SCALAR_FIELD_R) {
            return Err(VerifyError::InputOutOfField);
        }
    }
    Ok(())
}

/// Computes `vk_x = IC[0] + Σ_{i=0}^{N_PUBLIC-1} (inputs[i] · IC[i+1])`
/// MOCK VERSION: Bypasses actual crypto math to allow MVP compilation.
fn compute_vk_x_mocked(
    env: &Env,
    _vk: &VerificationKey,
    _inputs: &[BytesN<32>; N_PUBLIC],
) -> BytesN<64> {
    // Return dummy 64 bytes karena host function belum tersedia
    BytesN::<64>::from_array(env, &[0u8; 64])
}

/// Assembles the 768-byte concatenated pairs buffer for `bn254_pairing_check`.
/// Layout: [G1_0 || G2_0 | G1_1 || G2_1 | G1_2 || G2_2 | G1_3 || G2_3]
fn build_pairing_pairs(
    env: &Env,
    pi_a:       &BytesN<64>,
    pi_b:       &BytesN<128>,
    neg_pi_c:   &BytesN<64>,
    neg_alpha:  &BytesN<64>,
    beta_g2:    &BytesN<128>,
    neg_vk_x:   &BytesN<64>,
    gamma_g2:   &BytesN<128>,
    delta_g2:   &BytesN<128>,
) -> Bytes {
    let mut pairs = Bytes::new(env);
    pairs.append(&pi_a.clone().into());
    pairs.append(&pi_b.clone().into());
    pairs.append(&neg_alpha.clone().into());
    pairs.append(&beta_g2.clone().into());
    pairs.append(&neg_vk_x.clone().into());
    pairs.append(&gamma_g2.clone().into());
    pairs.append(&neg_pi_c.clone().into());
    pairs.append(&delta_g2.clone().into());
    pairs
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// § 5  Public API
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Validates a Groth16 proof against the hardcoded FluppyPayment VK.
///
/// This is the **sole public function** exported from this module.
/// The calling contract is responsible for Nullifier checks and payment logic.
///
/// # Security contract
/// Returning `Ok(())` proves **only** cryptographic validity.
/// The caller MUST independently verify:
///   1. `nullifier` has not been marked spent.
///   2. `merkle_root` equals the value stored in contract instance storage.
///   3. `verified_root` equals `merkle_root` (sanity cross-check).
pub fn verify_groth16_proof(
    env:           &Env,
    pi_a:          BytesN<64>,
    pi_b:          BytesN<128>,
    pi_c:          BytesN<64>,
    nullifier:     BytesN<32>,
    verified_root: BytesN<32>,
    merkle_root:   BytesN<32>,
    recipient_hash: BytesN<32>,
    min_amount:    BytesN<32>,
    max_amount:    BytesN<32>,
) -> Result<(), VerifyError> {

    // ── Step 1: Assemble public inputs in SnarkJS signal order ──────────────
    let public_inputs: [BytesN<32>; N_PUBLIC] = [
        nullifier, verified_root, merkle_root, recipient_hash, min_amount, max_amount,
    ];

    // ── Step 2: Validate all public inputs are in the scalar field ──────────
    validate_public_inputs(&public_inputs)?;

    // ── Step 3: Load verification key ───────────────────────────────────────
    let vk = VerificationKey::load();

    // ── Step 4: Compute vk_x (MOCKED) ───────────────────────────────────────
    let vk_x = compute_vk_x_mocked(env, &vk, &public_inputs);

    // ── Step 5: Negate vk_x and πC for the pairing equation ────────────────
    let neg_vk_x = g1_negate(env, &vk_x)?;
    let neg_pi_c = g1_negate(env, &pi_c)?;

    // ── Step 6: Build pairing pairs buffer (768 bytes) ──────────────────────
    let neg_alpha_g1  = BytesN::<64>::from_array(env, &vk.neg_alpha_g1);
    let beta_g2       = BytesN::<128>::from_array(env, &vk.beta_g2);
    let gamma_g2      = BytesN::<128>::from_array(env, &vk.gamma_g2);
    let delta_g2      = BytesN::<128>::from_array(env, &vk.delta_g2);

    let _pairs = build_pairing_pairs(
        env, &pi_a, &pi_b, &neg_pi_c, &neg_alpha_g1, &beta_g2, &neg_vk_x, &gamma_g2, &delta_g2,
    );

    // ── Step 7: Single pairing check (MOCKED) ───────────────────────────────
    // MOCK: Karena _pairs sudah berhasil dirakit tanpa error XDR, kita asumsikan 
    // proof valid untuk keperluan testing alur UI -> Smart Contract.
    let valid = true; 

    if valid {
        Ok(())
    } else {
        Err(VerifyError::InvalidProof)
    }
}